/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppSuccessStoriesRouteImport } from './routes/_app.success-stories'
import { Route as AppSchemesRouteImport } from './routes/_app.schemes'
import { Route as AppMarketplaceRouteImport } from './routes/_app.marketplace'
import { Route as AppHomeRouteImport } from './routes/_app.home'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppContactRouteImport } from './routes/_app.contact'
import { Route as AppBusinessIdeasRouteImport } from './routes/_app.business-ideas'
import { Route as AppAuthRouteImport } from './routes/_app.auth'
import { Route as AppAboutRouteImport } from './routes/_app.about'
import { Route as AppProductIdRouteImport } from './routes/_app.product.$id'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSuccessStoriesRoute = AppSuccessStoriesRouteImport.update({
  id: '/success-stories',
  path: '/success-stories',
  getParentRoute: () => AppRoute,
} as any)
const AppSchemesRoute = AppSchemesRouteImport.update({
  id: '/schemes',
  path: '/schemes',
  getParentRoute: () => AppRoute,
} as any)
const AppMarketplaceRoute = AppMarketplaceRouteImport.update({
  id: '/marketplace',
  path: '/marketplace',
  getParentRoute: () => AppRoute,
} as any)
const AppHomeRoute = AppHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppContactRoute = AppContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => AppRoute,
} as any)
const AppBusinessIdeasRoute = AppBusinessIdeasRouteImport.update({
  id: '/business-ideas',
  path: '/business-ideas',
  getParentRoute: () => AppRoute,
} as any)
const AppAuthRoute = AppAuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => AppRoute,
} as any)
const AppAboutRoute = AppAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => AppRoute,
} as any)
const AppProductIdRoute = AppProductIdRouteImport.update({
  id: '/product/$id',
  path: '/product/$id',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AppAboutRoute
  '/auth': typeof AppAuthRoute
  '/business-ideas': typeof AppBusinessIdeasRoute
  '/contact': typeof AppContactRoute
  '/dashboard': typeof AppDashboardRoute
  '/home': typeof AppHomeRoute
  '/marketplace': typeof AppMarketplaceRoute
  '/schemes': typeof AppSchemesRoute
  '/success-stories': typeof AppSuccessStoriesRoute
  '/product/$id': typeof AppProductIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AppAboutRoute
  '/auth': typeof AppAuthRoute
  '/business-ideas': typeof AppBusinessIdeasRoute
  '/contact': typeof AppContactRoute
  '/dashboard': typeof AppDashboardRoute
  '/home': typeof AppHomeRoute
  '/marketplace': typeof AppMarketplaceRoute
  '/schemes': typeof AppSchemesRoute
  '/success-stories': typeof AppSuccessStoriesRoute
  '/product/$id': typeof AppProductIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_app/about': typeof AppAboutRoute
  '/_app/auth': typeof AppAuthRoute
  '/_app/business-ideas': typeof AppBusinessIdeasRoute
  '/_app/contact': typeof AppContactRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/home': typeof AppHomeRoute
  '/_app/marketplace': typeof AppMarketplaceRoute
  '/_app/schemes': typeof AppSchemesRoute
  '/_app/success-stories': typeof AppSuccessStoriesRoute
  '/_app/product/$id': typeof AppProductIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/business-ideas'
    | '/contact'
    | '/dashboard'
    | '/home'
    | '/marketplace'
    | '/schemes'
    | '/success-stories'
    | '/product/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/business-ideas'
    | '/contact'
    | '/dashboard'
    | '/home'
    | '/marketplace'
    | '/schemes'
    | '/success-stories'
    | '/product/$id'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_app/about'
    | '/_app/auth'
    | '/_app/business-ideas'
    | '/_app/contact'
    | '/_app/dashboard'
    | '/_app/home'
    | '/_app/marketplace'
    | '/_app/schemes'
    | '/_app/success-stories'
    | '/_app/product/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/success-stories': {
      id: '/_app/success-stories'
      path: '/success-stories'
      fullPath: '/success-stories'
      preLoaderRoute: typeof AppSuccessStoriesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/schemes': {
      id: '/_app/schemes'
      path: '/schemes'
      fullPath: '/schemes'
      preLoaderRoute: typeof AppSchemesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/marketplace': {
      id: '/_app/marketplace'
      path: '/marketplace'
      fullPath: '/marketplace'
      preLoaderRoute: typeof AppMarketplaceRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/home': {
      id: '/_app/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AppHomeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/contact': {
      id: '/_app/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof AppContactRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/business-ideas': {
      id: '/_app/business-ideas'
      path: '/business-ideas'
      fullPath: '/business-ideas'
      preLoaderRoute: typeof AppBusinessIdeasRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/auth': {
      id: '/_app/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AppAuthRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/about': {
      id: '/_app/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AppAboutRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/product/$id': {
      id: '/_app/product/$id'
      path: '/product/$id'
      fullPath: '/product/$id'
      preLoaderRoute: typeof AppProductIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAboutRoute: typeof AppAboutRoute
  AppAuthRoute: typeof AppAuthRoute
  AppBusinessIdeasRoute: typeof AppBusinessIdeasRoute
  AppContactRoute: typeof AppContactRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppHomeRoute: typeof AppHomeRoute
  AppMarketplaceRoute: typeof AppMarketplaceRoute
  AppSchemesRoute: typeof AppSchemesRoute
  AppSuccessStoriesRoute: typeof AppSuccessStoriesRoute
  AppProductIdRoute: typeof AppProductIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAboutRoute: AppAboutRoute,
  AppAuthRoute: AppAuthRoute,
  AppBusinessIdeasRoute: AppBusinessIdeasRoute,
  AppContactRoute: AppContactRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppHomeRoute: AppHomeRoute,
  AppMarketplaceRoute: AppMarketplaceRoute,
  AppSchemesRoute: AppSchemesRoute,
  AppSuccessStoriesRoute: AppSuccessStoriesRoute,
  AppProductIdRoute: AppProductIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
