/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppSuccessStoriesRouteImport } from './routes/_app.success-stories'
import { Route as AppSchemesRouteImport } from './routes/_app.schemes'
import { Route as AppMarketplaceRouteImport } from './routes/_app.marketplace'
import { Route as AppHomeRouteImport } from './routes/_app.home'
import { Route as AppBusinessIdeasRouteImport } from './routes/_app.business-ideas'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSuccessStoriesRoute = AppSuccessStoriesRouteImport.update({
  id: '/success-stories',
  path: '/success-stories',
  getParentRoute: () => AppRoute,
} as any)
const AppSchemesRoute = AppSchemesRouteImport.update({
  id: '/schemes',
  path: '/schemes',
  getParentRoute: () => AppRoute,
} as any)
const AppMarketplaceRoute = AppMarketplaceRouteImport.update({
  id: '/marketplace',
  path: '/marketplace',
  getParentRoute: () => AppRoute,
} as any)
const AppHomeRoute = AppHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AppRoute,
} as any)
const AppBusinessIdeasRoute = AppBusinessIdeasRouteImport.update({
  id: '/business-ideas',
  path: '/business-ideas',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/business-ideas': typeof AppBusinessIdeasRoute
  '/home': typeof AppHomeRoute
  '/marketplace': typeof AppMarketplaceRoute
  '/schemes': typeof AppSchemesRoute
  '/success-stories': typeof AppSuccessStoriesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/business-ideas': typeof AppBusinessIdeasRoute
  '/home': typeof AppHomeRoute
  '/marketplace': typeof AppMarketplaceRoute
  '/schemes': typeof AppSchemesRoute
  '/success-stories': typeof AppSuccessStoriesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_app/business-ideas': typeof AppBusinessIdeasRoute
  '/_app/home': typeof AppHomeRoute
  '/_app/marketplace': typeof AppMarketplaceRoute
  '/_app/schemes': typeof AppSchemesRoute
  '/_app/success-stories': typeof AppSuccessStoriesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/business-ideas'
    | '/home'
    | '/marketplace'
    | '/schemes'
    | '/success-stories'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/business-ideas'
    | '/home'
    | '/marketplace'
    | '/schemes'
    | '/success-stories'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_app/business-ideas'
    | '/_app/home'
    | '/_app/marketplace'
    | '/_app/schemes'
    | '/_app/success-stories'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/success-stories': {
      id: '/_app/success-stories'
      path: '/success-stories'
      fullPath: '/success-stories'
      preLoaderRoute: typeof AppSuccessStoriesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/schemes': {
      id: '/_app/schemes'
      path: '/schemes'
      fullPath: '/schemes'
      preLoaderRoute: typeof AppSchemesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/marketplace': {
      id: '/_app/marketplace'
      path: '/marketplace'
      fullPath: '/marketplace'
      preLoaderRoute: typeof AppMarketplaceRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/home': {
      id: '/_app/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AppHomeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/business-ideas': {
      id: '/_app/business-ideas'
      path: '/business-ideas'
      fullPath: '/business-ideas'
      preLoaderRoute: typeof AppBusinessIdeasRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppBusinessIdeasRoute: typeof AppBusinessIdeasRoute
  AppHomeRoute: typeof AppHomeRoute
  AppMarketplaceRoute: typeof AppMarketplaceRoute
  AppSchemesRoute: typeof AppSchemesRoute
  AppSuccessStoriesRoute: typeof AppSuccessStoriesRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppBusinessIdeasRoute: AppBusinessIdeasRoute,
  AppHomeRoute: AppHomeRoute,
  AppMarketplaceRoute: AppMarketplaceRoute,
  AppSchemesRoute: AppSchemesRoute,
  AppSuccessStoriesRoute: AppSuccessStoriesRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
